### ISSUE TITLE
Thank you and question

### ISSUE THREAD

**Issue by hoenth** [andyjeffries/flexirest#1]
First, thank you Andy for taking over and continuing development of FlexiRest (formally ActiveRestClient). As restful API's proliferate, having tools for consuming them based on conventions versus configurations become ever more important. 

This is not an issue, but a question on best practices.

I need to add values to the body of all my requests. A Configuration module contains methods for setting and getting the userid and source values. Currently, I am doing the following. 

```ruby
module MyRestClient
  class Base < FlexiRest::Base
    include Configuration
    def initialize(args = {})
      super
      self.userid = self.class.userid
      self.source = self.class.source
    end

  end
end

module MyRestClient
  class Product < Base
    post :create, "/products"
  end
end
```

Is this the preferred method, or would you recommend another?

**Comment by andyjeffries** [comment]
Sorry for the delay @hoenth, I apparently wasn't watching my own repository so I only noticed this issue when I came to look at the PR your emailed me about.

Given that you don't know at the point of defining your `userid`/`source` whether they'll be post or get variables, I think this is a sensible solution.  I personally would put the `super` after the initialisation of the variables (otherwise they will always override those variables if they happen to be set in a subclass), but that may be what you want.

The other solution would be a `before_request` callback on a base class, but to do that you'd need to know if they were always going to post or get variables.
